title: p2panda
author: p2panda
tagline: Building blocks for autonomous peer-to-peer applications
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://p2panda.org"

plugins:
  - jekyll-feed
